// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOzfzclhSADobjxfjOTsjWpYhD1RMLd_s',
    appId: '1:660486127525:web:b43f668019e3e6294f724c',
    messagingSenderId: '660486127525',
    projectId: 'seo-manager-66526',
    authDomain: 'seo-manager-66526.firebaseapp.com',
    storageBucket: 'seo-manager-66526.firebasestorage.app',
    measurementId: 'G-6M2ET1PRLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHE_a-rkusK8jkjjQttwlp65XN27LlVU',
    appId: '1:660486127525:android:b925cb45c1eb48a64f724c',
    messagingSenderId: '660486127525',
    projectId: 'seo-manager-66526',
    storageBucket: 'seo-manager-66526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB239XGfYCPJWT0dRjnvnz6wEjr0f_lVe0',
    appId: '1:660486127525:ios:90b0249967787a1a4f724c',
    messagingSenderId: '660486127525',
    projectId: 'seo-manager-66526',
    storageBucket: 'seo-manager-66526.firebasestorage.app',
    iosBundleId: 'com.example.authorityTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB239XGfYCPJWT0dRjnvnz6wEjr0f_lVe0',
    appId: '1:660486127525:ios:90b0249967787a1a4f724c',
    messagingSenderId: '660486127525',
    projectId: 'seo-manager-66526',
    storageBucket: 'seo-manager-66526.firebasestorage.app',
    iosBundleId: 'com.example.authorityTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOzfzclhSADobjxfjOTsjWpYhD1RMLd_s',
    appId: '1:660486127525:web:1f9709dfb5e8e3de4f724c',
    messagingSenderId: '660486127525',
    projectId: 'seo-manager-66526',
    authDomain: 'seo-manager-66526.firebaseapp.com',
    storageBucket: 'seo-manager-66526.firebasestorage.app',
    measurementId: 'G-H9Q6YC30PP',
  );
}
