// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBixe34-2GiZ1xqlSv2BNDWtZDInEcS4',
    appId: '1:1051440179499:web:09c469050d02b4e417fd6e',
    messagingSenderId: '1051440179499',
    projectId: 'authority-tracker',
    authDomain: 'authority-tracker.firebaseapp.com',
    storageBucket: 'authority-tracker.firebasestorage.app',
    measurementId: 'G-V8KNZB8TS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBFHA9NLGY_3soR8Yr5GbeNBZUOoSFdHQ',
    appId: '1:1051440179499:android:78cb9f99f0715b6a17fd6e',
    messagingSenderId: '1051440179499',
    projectId: 'authority-tracker',
    storageBucket: 'authority-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAsEXSdj0HuJ7tM3cZi4-ZvSw7kZNUpg',
    appId: '1:1051440179499:ios:939b19db323c2a3517fd6e',
    messagingSenderId: '1051440179499',
    projectId: 'authority-tracker',
    storageBucket: 'authority-tracker.firebasestorage.app',
    iosBundleId: 'com.example.authorityTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAsEXSdj0HuJ7tM3cZi4-ZvSw7kZNUpg',
    appId: '1:1051440179499:ios:939b19db323c2a3517fd6e',
    messagingSenderId: '1051440179499',
    projectId: 'authority-tracker',
    storageBucket: 'authority-tracker.firebasestorage.app',
    iosBundleId: 'com.example.authorityTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLBixe34-2GiZ1xqlSv2BNDWtZDInEcS4',
    appId: '1:1051440179499:web:68c1773ed4eb2cc817fd6e',
    messagingSenderId: '1051440179499',
    projectId: 'authority-tracker',
    authDomain: 'authority-tracker.firebaseapp.com',
    storageBucket: 'authority-tracker.firebasestorage.app',
    measurementId: 'G-K8THXSCXDG',
  );

}